### ISSUE TITLE
Specify the difference between idea and concept in the feature overview

### ISSUE THREAD

**Issue by FraMecca** [inexorgame/site#43]
[This page](https://inexor.org/wiki/features/) shows four labels but their meaning may not be obvious for all readers.
I find Idea / Concept especially confusing and their difference should be stated.

**Comment by MartinMuzatko** [comment]
Hey there! thanks for the feedback.

Since we are at the beginning of labeling the feature correctly - your help is appreciated :)

It describes a maturity level.
It might also make sense to distinguish between an issue and a feature. Usually a feature can span multiple repos, multiple parts or services of a system. Issues are usually more specific (smaller scope) and to the point.

### Types
* **IDEA:** This can be as minimal as a suggestion, but does not necessarily need to describe all touching parts. E.g.: I want a way of managing my clan
* **CONCEPT:** Conceptualizes which parts of the system need to be touched. E.g. This is what the UI should have, this is what the underlying servers need to do.
* **SPECIFICATION:** Full specifications are as complete as possible documentations for implementors. The [entity system](https://hackmd.io/6glkB2UoQsKcWfVhGasVoA#Entity-System-Modularity) is a good example.
* **IMPLEMENTED:**


I will add these infos to the wiki. 👍
